### ISSUE TITLE
Only shows white window

### ISSUE THREAD

**Issue by probonopd** [pathephone/pathephone-desktop#116]
On Xubuntu 16.04 `pathephone-desktop-1.0.0-x86_64.AppImage` only shows a white window:
 
![](https://user-images.githubusercontent.com/2480569/35702973-7d80da4e-0792-11e8-9e65-8dfd7d63f81f.png)

**Comment by DEgITx** [comment]
I checked, probably AppImage image broken
on windows release build broken too, probably Travis builder problem

**Comment by negamaxi** [comment]
Local builds broken too.

**Comment by negamaxi** [comment]
Cannot find module 'styled-jsx/style'

**Comment by negamaxi** [comment]
@probonopd fixed, check the latest 0.4.0 builds.

**Comment by probonopd** [comment]
Thank you.
