### ISSUE TITLE
Semantic-release changelog plugin

### ISSUE THREAD

**Issue by negamaxi** [pathephone/pathephone-desktop#129]

**Comment by DEgITx** [comment]
я оставлю тут его, на всякий случай, если вдруг не прокатит
[.releaserc.json](https://github.com/pathephone/pathephone-desktop/files/1693411/releaserc.txt)

**Comment by DEgITx** [comment]
у тебя там мастер от пушей заблочен, вот оно и не вкомичивает вроде бы поэтому
