### ISSUE TITLE
Command Failed at startup

### ISSUE THREAD

**Issue by Porco-Rosso** [pathephone/pathephone-desktop#143]
As of right now (v1.0.3) trying to run the MacOS version (zip) of the app givest the error below https://github.com/pathephone/pathephone-desktop/releases/tag/v1.0.3

````
COMMAND FAILED: /PRIVATE/VAR/FOLDERS/G2/SZ356XZJ5MB9K880GP9K5F1M0000GN/T/APPTRANSLOCATION/61EA9DA0-9272-449C-9FD1-0CA53FA0BFD5/D/PATHEPHONE 2.APP/CONTENTS/MACOS/IPFS REPO FSCK /BIN/SH: /PRIVATE/VAR/FOLDERS/G2/SZ356XZJ5MB9K880GP9K5F1M0000GN/T/APPTRANSLOCATION/61EA9DA0-9272-449C-9FD1-0CA53FA0BFD5/D/PATHEPHONE: NO SUCH FILE OR DIRECTORY
````
Edit: The .dmg version gets stuck at `IPFS DAEMON`

**Comment by Porco-Rosso** [comment]
Even more curiously, running the .zip release while the dmg version is stuck leads to the message `UNKNOWN` after briefly displaying rxdb initializing

**Comment by negamaxi** [comment]
@Porco-Rosso Thanks for the issue. Any success with v1.0.0?

**Comment by DEgITx** [comment]
I checked 1.0.3, all working on Mac: dmg and zip, if not than delete ~/Library/Application Support/Pathephone directory

There no albums because we are only at begining of Pathephone infrastructure build, as soon there will be users there also will be albums.

**Comment by Porco-Rosso** [comment]
On Mac OS High Sierra 10.13.2, with the dmg I get still get the IPFS daemon issue, and with the zip I get the command failed error. 

Deleting the folder had no effect on either, and running IPFS daemon for the terminal and then launching pathephone, just gave me a message asking me to shutdown the dameon before running the app.

**Comment by Porco-Rosso** [comment]
Updating my local install of ipfs using `ipfs-update install v0.4.13` did the trick and now pathephone is working.
Thanks for the help, although I am confused: shouldn't pathephone use an internal version of ipfs? Are users supposed to install ipfs as a dependency first?

**Comment by negamaxi** [comment]
@Porco-Rosso internal version definitely should work. Seems like I was messing up with some internals rewritten this week. Therefore reopen.

**Comment by negamaxi** [comment]
@Porco-Rosso check the latest and let us know if the issue resolved.

**Comment by negamaxi** [comment]
@DrewCyber need some help with macOS testing, check https://github.com/pathephone/pathephone-desktop/releases/tag/v1.0.4 dmg + zip for errors on startup if possible.

**Comment by DrewCyber** [comment]
Both versions (dmg and zip) start correctly.
On start it asks "Do you want the application “ipfs” to accept incoming network connections?".
