### ISSUE TITLE
Loading indication when uploading files

### ISSUE THREAD

**Issue by viktorfa** [pathephone/pathephone-desktop#149]
Should have some loading wheel or something when uploading files. I was confused and thought it maybe froze. 

Using on Linux Mint 18.3 installed with .deb package.

**Comment by negamaxi** [comment]
@viktorfa, do you mean clicking "add tracks" button or "done"?

**Comment by DEgITx** [comment]
on "add tracks" there are loading wheel by the way

**Comment by viktorfa** [comment]
It's only when adding files with the 'add tracks' button. After selecting files in the system dialog, there is no loading icon, but the files will eventually appear in Pathephone.

When using drag-and-drop, the loading icon appears correctly (spinning arrow).

**Comment by negamaxi** [comment]
@viktorfa still actual for v1.2.1?
