### ISSUE TITLE
MacOS menubar icon

### ISSUE THREAD

**Issue by Porco-Rosso** [pathephone/pathephone-desktop#164]
I suspect this is not how the menubar icon is supposed to look? 
<img width="164" alt="screen shot 2018-05-10 at 12 34 53 pm" src="https://user-images.githubusercontent.com/7024527/39863245-ca1c78fa-544e-11e8-942e-19daef782f0d.png">

I suspect the image is not being scaled down as it should be.
Also I suggest using a monochrome icon (light and dark theme) so it feels more native on macOS at least.

**Comment by negamaxi** [comment]
@Porco-Rosso thanks for your response. Indeed we should create a special tray icon, now a default launcher icon is used.

**Comment by negamaxi** [comment]
@Porco-Rosso please check the latest version, should be fixed https://github.com/pathephone/pathephone-desktop/releases/tag/v1.4.0

**Comment by Porco-Rosso** [comment]
<img width="200" alt="screen shot 2018-06-22 at 2 26 01 pm" src="https://user-images.githubusercontent.com/7024527/41774390-3f5c7c50-7628-11e8-9057-187b1bb553a3.png">
The image now fits better, but on a retina display the resolution is still lacking (doesn't show well on the screenshot) and the icon should probably be sized down. Anyway, you can close this issue, as I guess it was solved.

**Comment by negamaxi** [comment]
@Porco-Rosso, I'll give some top/bottom padding on the next release and try to increase resolution.

**Comment by negamaxi** [comment]
@Porco-Rosso check out the [latest release](https://github.com/pathephone/pathephone-desktop/releases/tag/v2.0.0). It's shipped with a 2x icon that should be used on retina displays according to Electron docs. Also new icon smaller and should fit better. At least on Linux with appindicator support, it fit well.
![pathetray](https://user-images.githubusercontent.com/16529171/42335970-d0325986-808a-11e8-89a1-7ff83f9073c2.png)

**Comment by Porco-Rosso** [comment]
@negamaxi Unfortunately the problem seems to persist. The resolution does seem better, but the padding is not present on MacOS. Also when the window is open, the menubar icon remains highlighted, regardless of clicking elsewhere.
<img width="322" alt="screen shot 2018-07-06 at 2 42 54 pm" src="https://user-images.githubusercontent.com/7024527/42377202-0337b146-812b-11e8-8627-e5dc4183dd8d.png">
