### ISSUE TITLE
ONLY ONE USAGE OF EACH SOCKET ADDRESS IS NORMALLY PERMITTED.

### ISSUE THREAD

**Issue by NatoBoram** [pathephone/pathephone-desktop#174]
> IPFS-GET-INFO: NON-ZERO EXIT CODE 1 WHILE RUNNING: C:\USERS\NATOB\APPDATA\LOCAL\PROGRAMS\PATHEPHONE-DESKTOP\RESOURCES\APP.ASAR\NODE_MODULES\SUBCOMANDANTE\SUBCOM 9108 C:\USERS\NATOB\APPDATA\LOCAL\PROGRAMS\PATHEPHONE-DESKTOP\RESOURCES/GO-IPFS/IPFS.EXE DAEMON --ENABLE-PUBSUB-EXPERIMENT [0;37M19:29:00.587 [31MERROR [0;34M CMD/IPFS: [0MERROR FROM NODE CONSTRUCTION: FAILED TO LISTEN ON ANY ADDRESSES: [LISTEN TCP4 0.0.0.0:4001: BIND: ONLY ONE USAGE OF EACH SOCKET ADDRESS (PROTOCOL/NETWORK ADDRESS/PORT) IS NORMALLY PERMITTED. LISTEN TCP6 [::]:4001: BIND: ONLY ONE USAGE OF EACH SOCKET ADDRESS (PROTOCOL/NETWORK ADDRESS/PORT) IS NORMALLY PERMITTED.] [0;37MEXECUTOR.GO:108[0M ERROR: FAILED TO LISTEN ON ANY ADDRESSES: [LISTEN TCP4 0.0.0.0:4001: BIND: ONLY ONE USAGE OF EACH SOCKET ADDRESS (PROTOCOL/NETWORK ADDRESS/PORT) IS NORMALLY PERMITTED. LISTEN TCP6 [::]:4001: BIND: ONLY ONE USAGE OF EACH SOCKET ADDRESS (PROTOCOL/NETWORK ADDRESS/PORT) IS NORMALLY PERMITTED.]

Windows 10 Version 1803 Build 17134.137

![image](https://user-images.githubusercontent.com/10495562/42425158-af9e7e3a-82e6-11e8-97e2-32d52291c122.png)

It looks like you try to create an IPFS node by yourself. If you do that, use your own socket. Or, you know, just use my node : it's free, and compiled from source!

**Comment by negamaxi** [comment]
@NatoBoram fair enough)

**Comment by NatoBoram** [comment]
Using `Pathephone.Setup.2.1.0.exe`

![winver](https://user-images.githubusercontent.com/10495562/43933212-57018e4a-9c16-11e8-9540-790403c39e4b.PNG)

![pathephone](https://user-images.githubusercontent.com/10495562/43932901-a98fc7dc-9c14-11e8-9d0d-1e0ec0f40ee8.PNG)

**Comment by negamaxi** [comment]
@NatoBoram I'll reopen this. Seems like it's not a gateway/API port conflict. Can you provide me with exact steps to reproduce this on my system?

**Comment by NatoBoram** [comment]
1. Windows 10, fresh install
2. Install Go
3. Add `%UserProfile%\Go` to `PATH`
4. `go get -u -v -fix github.com/ipfs/ipfs-update`
5. In `%UserProfile%\Go\`, `ipfs-update fetch latest` and rename the download file to `ipfs.exe`
6. `ipfs init`
7. Add a planned task to start `ipfs daemon` on user startup
8. Reboot
9. Check that IPFS is running by opening a browser with the IPFS Companion
10. Install pathephone-desktop
11. `ONLY ONE USAGE OF EACH SOCKET ADDRESS IS NORMALLY PERMITTED`
