### ISSUE TITLE
Allow using existing ipfs daemon

### ISSUE THREAD

**Issue by mkg20001** [pathephone/pathephone-desktop#178]
Pathephone fails to start if another ipfs instance is already running. It should be possible to just use the running one instead of launching a new one.

**Comment by negamaxi** [comment]
@mkg20001 Pathephone requires some experimental options to be set (pub/sub or filestore in future releases). There is another option to just use different API / gateway port to avoid conflicts with existing nodes, but it's not possible for now.

**Comment by negamaxi** [comment]
@mkg20001 should be fixed in 2.1.0. Please check it out and let me know if the issue remains.
