### ISSUE TITLE
Get album cover from files

### ISSUE THREAD

**Issue by mkg20001** [pathephone/pathephone-desktop#179]
Currently when adding files the album name and artist are correctly extracted from the files (:+1:). Yet the cover isn't. Would it be possible to add that too?

**Comment by negamaxi** [comment]
@mkg20001 why not, should be easy.

**Comment by NatoBoram** [comment]
That's great! It was strange to have to put a random image on purchased music files.

**Comment by mkg20001** [comment]
Nice!
