### ISSUE TITLE
Can't play local albums immediately

### ISSUE THREAD

**Issue by drudoi** [pathephone/pathephone-desktop#181]
I've installed .appimage app for linux and added some albums, but I can't listen it in the app immediately. I've wait for 5 minutes - but the songs from the album haven't played!

**Comment by negamaxi** [comment]
@drudoi is there any other albums received besides the ones you add manually?

**Comment by negamaxi** [comment]
@drudoi the bug that caused this behavior should be fixed in [v2.0.2](https://github.com/pathephone/pathephone-desktop/releases/tag/v2.0.2). Please check it out and give me a feedback.
