### ISSUE TITLE
Crash on OS X

### ISSUE THREAD

**Issue by danyisill** [pathephone/pathephone-desktop#182]
![2018-07-18 6 43 11](https://user-images.githubusercontent.com/23189912/42858164-da4e8262-8a55-11e8-8130-dc24d3b6ef8c.png)

**Comment by negamaxi** [comment]
@danyisill could you copy-paste here the whole error message?

**Comment by negamaxi** [comment]
@danyisill probably related to https://github.com/electron/electron/issues/13404#issuecomment-401406040

Check out the latest 2.0.2 Pathephone build. It uses Electron 2.0.5 that shouldn't be affected.

**Comment by danyisill** [comment]
Seems to work fine now.
