### ISSUE TITLE
CRITICAL ERROR: "Support pathephone" button doesn't work!

### ISSUE THREAD

**Issue by uniconstructor** [pathephone/pathephone-desktop#183]
OMG, you definitely should better test this important logic! :) 

### Technical details
Installed Package: pathephone-desktop_2.0.0_amd64.deb
OS: Ubuntu 16.04

How to reproduce:
1) Open app
2) Find "support Pathephone development" screen
3) Select VISA payment method, enter sum, (Yandex payment page will open)
4) Fill out payment data
5) Click "make payment"
6) Nothing happens. No error, no response: payment page just ignores me. 

Dear pathephone developers, I am very disappointed! 

# I SAID SHUT UP AND TAKE MY MONEY!

**Comment by uniconstructor** [comment]
And also: cryptocurrency name misspelled: "Bitcoin **Cash**", not "Bitcoin **Cache**"

**Comment by negamaxi** [comment]
@uniconstructor, the best. issue. ever) thanks, will take a look.
