### ISSUE TITLE
[Question] Does global discovery work out of the box?

### ISSUE THREAD

**Issue by brasilikum** [pathephone/pathephone-desktop#221]
I have a question around discovery:
Is it just supposed to work globally? Should I see something other than my own albums in the discover tab or do I need do have someone on my local network for this to work?

**Comment by negamaxi** [comment]
@brasilikum sure, it works out of the box, but there is no constant userbase yet. To make sure everything is ok try to run another Pathephone instance somewhere on the internet (or locally, even without internet connection), share some music and wait for a while.

**Comment by brasilikum** [comment]
Would it make sense to have one machine constantly running just so people do not have the same experience I have? 
That might help to overcome the initial lack of users, as it is less likely that people start using it if there is nothing available.
I am talking a 5$ machine for a month or something until there is at least one person online at a time. Would that be enough?

**Comment by negamaxi** [comment]
@brasilikum it's a reasonable idea indeed, once Pathephone will be ready for daily usage as a desktop player we'll probably create some kind of a bootstrap server.

**Comment by brasilikum** [comment]
I tried on a second mac on the same network and I could not get it to work. As the image shows, it is uploading and downloading but the album does not show up on the other mac.
I had it open for ca 20 minutes, that should be enough for something to show up, no?

![img_8973](https://user-images.githubusercontent.com/3106990/44765388-15eaaa00-ab1a-11e8-9646-2ad2ae758aed.JPG)

**Comment by negamaxi** [comment]
@brasilikum it depends. IPFS is a very unpredictable technology in terms of 1-1 communication. In my own experience, it took about a minute. At the same time, there were situations when I was unable to discover albums at all.

**Comment by brasilikum** [comment]
Ok, in this case it sounds like a solution has to be found upstream.
I understand that it is out of your range, but for the usecase of pathephone it seems like a very unfortunate limitation.

BTW I just discovered the first albums that were not mine
