### ISSUE TITLE
No UI on mac

### ISSUE THREAD

**Issue by DrewCyber** [pathephone/pathephone-desktop#50]
Pathephone started, icon appears in dock, but I can't see UI on screen.

<img width="283" alt="menu" src="https://user-images.githubusercontent.com/21033043/33846724-b2d02a16-deb0-11e7-845f-bb008f9af000.png">

Pathephone v 0.2.3
macOS High Sierra 10.13.1 (17B1003)

**Comment by DEgITx** [comment]
we will test on mac soon :), thx for responce

**Comment by negamaxi** [comment]
@DrewCyber check out this builds, probably fixed https://github.com/pathephone/pathephone-desktop/releases/tag/%40dev-macos-tests-fix

**Comment by DrewCyber** [comment]
Ok. GUI appeared. You can resolve issue.
Is there any albums by default? "No albums found yet" on screen.

**Comment by DEgITx** [comment]
@DrewCyber library will be auto-update when will be enough users who publish albums. But probably we will make default library by default in feature at the start (24-hours node or something other).
