### ISSUE TITLE
In some cases ipfs methods takes too long

### ISSUE THREAD

**Issue by negamaxi** [pathephone/pathephone-desktop#98]
Видел на ipfs.id(), pubsub.subscribe(), dag.put(). Самое заметное случается с формой при добавлении альбома когда долго модалка не пропадает, но если закрыть и нщё раз открыть, то она сама сразу закроется и альбом добавится. Думаю из-за этой херни тесты и валятся.

**Comment by DEgITx** [comment]
я тут пока немного потыкал, как ни странно проблема не в ipfs или ipfs-api, вроде проблема в 6a08dab65a80baf0684c3816b26a3d2ca26f53f5 комите, пытаюсь пока понять что может так прерывать работу с апишкой
